//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class czlonek
    {
        public czlonek()
        {
            this.platnosci = new HashSet<platnosci>();
        }
    
        public int id { get; set; }
        public int id_klienta { get; set; }
        public int typ_czlonkowstwa { get; set; }
        public System.DateTime data_przystapienia { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual typ_czlonka typ_czlonka { get; set; }
        public virtual ICollection<platnosci> platnosci { get; set; }
    }
}
