//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IOEntities : DbContext
    {
        public IOEntities()
            : base("name=IOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<czlonek> czlonek { get; set; }
        public DbSet<grupy_pracownikow> grupy_pracownikow { get; set; }
        public DbSet<klient> klient { get; set; }
        public DbSet<platnosci> platnosci { get; set; }
        public DbSet<pracownik> pracownik { get; set; }
        public DbSet<samochod> samochod { get; set; }
        public DbSet<typ_czlonka> typ_czlonka { get; set; }
        public DbSet<typ_platnosci> typ_platnosci { get; set; }
        public DbSet<typ_zabiegu> typ_zabiegu { get; set; }
        public DbSet<typ_znizki> typ_znizki { get; set; }
        public DbSet<uprawnienia_czlonka> uprawnienia_czlonka { get; set; }
        public DbSet<wypozyczenia> wypozyczenia { get; set; }
        public DbSet<zabiegi_konserwacyjne> zabiegi_konserwacyjne { get; set; }
        public DbSet<znizki> znizki { get; set; }
        public DbSet<znizki_platnosci> znizki_platnosci { get; set; }
    }
}
