//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient
    {
        public klient()
        {
            this.czlonek = new HashSet<czlonek>();
            this.wypozyczenia = new HashSet<wypozyczenia>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string adres { get; set; }
        public string mail { get; set; }
        public int telefon { get; set; }
        public System.DateTime urodziny { get; set; }
    
        public virtual ICollection<czlonek> czlonek { get; set; }
        public virtual ICollection<wypozyczenia> wypozyczenia { get; set; }
    }
}
