//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class pracownik
    {
        public pracownik()
        {
            this.wypozyczenia = new HashSet<wypozyczenia>();
            this.zabiegi_konserwacyjne = new HashSet<zabiegi_konserwacyjne>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int id_grupy { get; set; }
        public string adres { get; set; }
        public string mail { get; set; }
        public int telefon { get; set; }
    
        public virtual grupy_pracownikow grupy_pracownikow { get; set; }
        public virtual ICollection<wypozyczenia> wypozyczenia { get; set; }
        public virtual ICollection<zabiegi_konserwacyjne> zabiegi_konserwacyjne { get; set; }
    }
}
