//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class typ_czlonka
    {
        public typ_czlonka()
        {
            this.czlonek = new HashSet<czlonek>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public int kwota { get; set; }
    
        public virtual ICollection<czlonek> czlonek { get; set; }
    }
}
