//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class wypozyczenia
    {
        public wypozyczenia()
        {
            this.platnosci = new HashSet<platnosci>();
        }
    
        public int id { get; set; }
        public int id_klienta { get; set; }
        public int id_samochodu { get; set; }
        public System.DateTime data_wypozyczenia { get; set; }
        public Nullable<System.DateTime> data_oddania { get; set; }
        public short rezerwacja { get; set; }
        public int id_pracownika { get; set; }
    
        public virtual klient klient { get; set; }
        public virtual ICollection<platnosci> platnosci { get; set; }
        public virtual pracownik pracownik { get; set; }
        public virtual samochod samochod { get; set; }
    }
}
