//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class zabiegi_konserwacyjne
    {
        public int id { get; set; }
        public int id_samochodu { get; set; }
        public int id_pracownika { get; set; }
        public System.DateTime data_rozpoczecia { get; set; }
        public Nullable<System.DateTime> data_zakonczenia { get; set; }
        public short wykonane { get; set; }
        public int typ_zabiegu_konserwacyjnego { get; set; }
        public string opis_zabiegu { get; set; }
    
        public virtual pracownik pracownik { get; set; }
        public virtual samochod samochod { get; set; }
    }
}
