//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IO_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class znizki
    {
        public znizki()
        {
            this.znizki_platnosci = new HashSet<znizki_platnosci>();
        }
    
        public int id { get; set; }
        public int id_typ_znizki { get; set; }
        public int procent { get; set; }
        public int kwota { get; set; }
        public short lacznosc { get; set; }
        public string opis { get; set; }
    
        public virtual typ_znizki typ_znizki { get; set; }
        public virtual ICollection<znizki_platnosci> znizki_platnosci { get; set; }
    }
}
